### ISSUE TITLE
Rename cke- prefix to ck- in the codebase

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui#112]
A follow-up of https://github.com/ckeditor/ckeditor5-ui-default/pull/122.

**Comment by Reinmar** [comment]
@oleq, I'm leaving it up to you whether we should have `ck-` or `cke-`.

**Comment by oleq** [comment]
I decided to go with `ck-` and I've been updating names (e.g. https://github.com/ckeditor/ckeditor5-image/pull/172/files) for some time now. Still, there are a couple of places left to fix.
