### ISSUE TITLE
Merge ui and ui-default

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui#116]
ckeditor5-ui is a framework and ckeditor5-ui-default implements the default UI library based on that framework. This separation looks reasonable but makes things complicated.

In order to allow extending the library we compiled it by merging these two packages and we were planning to allow to merge other `ckeditor5-ui-*` packages too. That would allow the developers to override the existing components easily. Unfortunately, this is hard to port to Webpack or other bundlers if we drop the compilation step.

Since both packages are available under `ckeditor5/ui/*` in the compiled version of the editor, we have troubles dropping the compilation now.

Besides that, it will be confusing what these two packages are about. While more editor-specific packages make for a clearer separation, claiming that we are developing framework and UI library may be not very intuitive.

Finally, there are two cases in which one wants to modify the UI library – either they want to replace it completely (so use the editing engine without all the rest) or change a bit some existing templates. The former is not a problem but the latter is. Extending/tuning the existing library is currently predicted, but I'm not sure if the cost isn't too high.

By merging these two packages we'll remove from the core architecture the ability to extend the UI library, but all bundlers support aliases, so, to some extent, such features should be still reachable.

OTOH, these two packages have clearly defined responsibilities and there was never a problem what to put where. So the other option is to not merge, but start referring to UI lib components  (i.e. importing them) as `ckeditor5-ui-default/sth` instead of `ckeditor5-ui/sth`. We'd keep the code separation and simplify the paths.

WDYT?

**Comment by oleq** [comment]
Your reasoning is quite clear, pros, cons, but... what is the actual source of this issue? What made you to create it?

**Comment by pjasiun** [comment]
:+1:

As long we do not implement another UI library we will not know if the separation makes sense. Learned by the experience, I do not believe it will work out of the box. We should prepare a `ckeditor5-ui-react` to prove it, but it would be too time-consuming at this point. I think that creating something like this would cause far more changes than we expect. At this stage keeping these packages separated, if we do not prove there is any profit, only make thinks more complicated.

Also, you can use the engine and plugins without the UI or with your fully custom UI overwriting UI part of plugins. You can also create a theme, fully change the appearance of the editor. To be honest I do not believe users need something in between.

**Comment by Reinmar** [comment]
> Your reasoning is quite clear, pros, cons, but... what is the actual source of this issue? What made you to create it?

The fact that the ckeditor5-ui-* merging feature is hard to develop for Webpack and Rollup if we drop compilation (and we're working on this now).

**Comment by Reinmar** [comment]
> As long we do not implement another UI library we will not know if the separation makes sense. Learned by the experience, I do not believe it will work out of the box. We should prepare a ckeditor5-ui-react to prove it, but it would be too time-consuming at this point. I think that creating something like this would cause far more changes than we expect. At this stage keeping these packages separated, if we do not prove there is any profit, only make thinks more complicated.

If you'd like to use React then you fall into the second category – totally replacing the whole editor UI – this is – including the "UI" parts of each feature.

The ckeditor5-ui-foo would need to use ckeditor5-ui so it's rather like a ckeditor5-ui-bootstrap or something.

**Comment by Reinmar** [comment]
PS. 

> As long we do not implement another UI library we will not know if the separation makes sense.

That's not really true and not the point. Implementing ckeditor5-ui-bootstrap is certainly totally doable. You just need to provide the same API – only the styling differs.

But you're right that we won't have time now to work on this which makes validating the whole concept hard on a different level – how to build all that.

But again, that's not the point. The point is that magical UI compilation is hard to implement in other ways than how we do it now.

**Comment by Reinmar** [comment]
My feelings about all this in a tweet: https://twitter.com/reinmarpl/status/811587433229877248

![image](https://cloud.githubusercontent.com/assets/156149/21394029/344b0854-c797-11e6-9e33-42d197d58216.png)

**Comment by pjasiun** [comment]
> > As long we do not implement another UI library we will not know if the separation makes sense.

> That's not really true and not the point. Implementing ckeditor5-ui-bootstrap is certainly totally doable. You just need to provide the same API – only the styling differs.

After all these refactorings we did I will never say that something is " certainly totally doable" before doing it ;) For instance, many plugins now inherit from UI classes and extends the template. Are you sure it will not be a problem if someone changes the template?

**Comment by Reinmar** [comment]
> Are you sure it will not be a problem if someone changes the template?

In these cases (when other components extend those base ones) it will be a problem. But it's then up to you to also fix those classes. Doable !== simple. I often see people ask for something to be trivial, while this is not the case. Allowing for something doesn't necessarily mean that it's at zero cost.

**Comment by Reinmar** [comment]
But I definitely agree about one thing – working on this "extensibility" with a real case in hands would give better results. Like with everything we did. So many mistakes were made because we simply had no idea what we're dealing with. I even remember my feeling when we were making the decisions to compile these UI libs in this way – I was super uncertain, felt totally blind and just needed to go forward with it :D.

**Comment by Reinmar** [comment]
OK, it seems that we made the decision to merge both packages. We'll need to do that urgently anyway, to not block working on new bundling methods.
