### ISSUE TITLE
Allow wrapping Template instances

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-ui#117]
Sometimes I need to wrap a template and keep the views interface:

```js
this.template = new Template( {
	tag: 'div',
	attributes: {
		class: 'button__wrapper'
	},
	children: [ this.template ]
} );
```

**Comment by oskarwrobel** [comment]
We have `Template.extends()` method for extending the template, maybe something like `Template.wrap()` will be more consistent.

**Comment by oskarwrobel** [comment]
But if this is only a workaround for https://github.com/ckeditor/ckeditor5-ui-default/issues/150 I think we should rethink tooltips first.

**Comment by pjasiun** [comment]
I think it might be useful in general. Sometimes you may need to wrap an element.

Note that this is enough to make it works: https://github.com/ckeditor/ckeditor5-ui/commit/d6eccb731e0b14ed1f842da4dbb786e36d0e00d9.

**Comment by pjasiun** [comment]
> We have Template.extends() method for extending the template, maybe something like Template.wrap() will be more consistent.

This was my first thought too. But then I realized that we use `Template.extends()` mostly because there is no simpler way of extending the template. Here we have a simpler way, so I don't think we should introduce a method if it is not needed.

Also, I don't think that it will be often case that someone wrap the template.

**Comment by pjasiun** [comment]
Also, if you reject this issue I can propose it as "Allow Template instance as a child of another template.". :P

**Comment by pjasiun** [comment]
This is a really nice issue. 

Because of it, I was not able to create a `WrappedButtonView` which wraps template of the `ButtonView`. It tools like ~1h to find the solotion. And ~1h to write a test which checks exactly putting one template into another. But... the test is passing event without this fix. So I spend the whole day trying to figure out why. Now @oleq, who is the author of this code, is trying to figure it out it and... everything what we have is that it might be somehow connected with the circular dependencies...

**Comment by oleq** [comment]
https://github.com/ckeditor/ckeditor5-ui/issues/118 implements the possibility of having `Template` directly as a child of another one. But please, use it carefully. If you wrap a `#template` of some `View` instance into another `Template`, then `view#element` points to the outermost in `Template` tree. So it may happen, that if the view uses `#element` internally to do some magic, it may fail because in DOM it points to a different `HTMLElement`.
