### ISSUE TITLE
BalloonPanel dissapears when selecting text inside with mouse ends outside of it

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui#122]
Moved from https://github.com/ckeditor/ckeditor5-ui-default/issues/132.

**Comment by Mgsy** [comment]
I'm not able to reproduce it anymore. @oleq, could I ask you to confirm?

**Comment by oleq** [comment]
Me neither. Probably fixed in https://github.com/ckeditor/ckeditor5-ui/issues/281.
