### ISSUE TITLE
Various View and Template class tests failing in Firefox

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui#13]
Tests which fail are 
 * http://tests.ckeditor.dev:1030/build/amd/tests/ui/template
 * http://tests.ckeditor.dev:1030/build/amd/tests/ui/view

It happens because the assertions are against `outerHTML` which is renders attributes in different order depending on the browser. Tests should be rewritten to assert `getAttribute( ... )`, `tagName`, `childNodes`, etc. instead. Some helper could be helpful.

**Comment by Reinmar** [comment]
I think it could make sense to create some helper: https://github.com/ckeditor/ckeditor5-utils/issues/19

**Comment by Reinmar** [comment]
In `--es5` build all tests pass. Interestingly, some template tests don't pass in ES6 mode... Curious what missing feature causes that.
