### ISSUE TITLE
InputTextView value change problem

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-ui#135]
Setting `InputTextView.value` property sets the value of the input element in DOM, but it is not updating when element content is changing. We currently have one-way data binding and this is how it suppose to work, but I found some issue:
![output](https://cloud.githubusercontent.com/assets/2396463/21765710/da0f5088-d66a-11e6-8f4f-9c43dfdfba42.gif)
(Note: link plugin have some other issue with input element updating but it will be reported in link plugin repository.)

What I found so far:
1. Before showing the balloon, `InputTextView` is updated by setting its value to `http://ckeditor.com`. 
2. DOM element is updated because its value is bind to view's value: https://github.com/ckeditor/ckeditor5-ui/blob/master/src/inputtext/inputtextview.js#L56
3. Balloon is showed and we write something in input element, but value of the `InputTextView` is not updated.
4. Close the balloon by clicking `Cancel`.
5. Clicking again on the same link is setting value of `InputTextView` again to `http://ckeditor.com`. It was never changed so the observer is not firing any events, so the DOM element is not updated and we end up with text from previous edit.

Thanks @oskarwrobel for help with this.

**Comment by Reinmar** [comment]
Just a quick question – isn't it enough to set the value of this input on every dialog open?

**Comment by oskarwrobel** [comment]
Nope. Input interface value is the same as command value but not the same as element.value. This is because changing html value does not change interface value.

**Comment by oskarwrobel** [comment]
Unless you asked about setting element.value on dialog open?

**Comment by szymonkups** [comment]
> Just a quick question – isn't it enough to set the value of this input on every dialog open?
We can do something like `inputTextView.element.value = 'foo bar'` to force the value, but then `inputTextView.value` will be useless.

**Comment by Reinmar** [comment]
I don't understand. In `InputTextView` I see:

```js
		this.on( 'change:value', ( evt, propertyName, value ) => this.element.value = value || '' );
```

So, what will happen if on balloon open we set `inputTextView.value` to the current value that should be displayed?

**Comment by szymonkups** [comment]
The value has the same value as on previous call (because it is not updated when we type into DOM element), so the event is not dispatched if I understand everything correctly.

**Comment by Reinmar** [comment]
OK... thanks :) Now it's clear.

**Comment by oleq** [comment]
## Easy solution

Just a fix in https://github.com/ckeditor/ckeditor5-link/issues/78, which would look like this:

```diff
diff --git a/src/link.js b/src/link.js
index 9c910be..589077a 100644
--- a/src/link.js
+++ b/src/link.js
@@ -244,6 +244,14 @@ export default class Link extends Plugin {
 	 * @return {Promise} A promise resolved when the {@link #formView} {@link module:ui/view~View#init} is done.
 	 */
 	_showPanel( focusInput ) {
+		console.log( this.editor.commands.get( 'link' ).value );
+		// Ensure each time the panel is shown, it remains in sync with the value of the command.
+		// Without it, if user typed in the input, then canceled the panel (`urlInputView#value`
+		// unchanged) and re-opened it without changing the value of the link command (i.e. clicked
+		// the same link), they would see the text they typed instead of clean value of the command.
+		// https://github.com/ckeditor/ckeditor5-link/issues/78
+		this.formView.urlInputView.inputView.element.value = this.editor.commands.get( 'link' ).value;
+
 		if ( this._balloon.hasView( this.formView ) ) {
 			// Check if formView should be focused and focus it if is visible.
 			if ( focusInput && this._balloon.visibleView === this.formView ) {
```

Or maybe you had something else in your mind?

We may create some syntax sugar for 
```js
this.formView.urlInputView.inputView.element.value = this.editor.commands.get( 'link' ).value
``` 
like `this.formView.urlInputView.inputView.sync()` or even `this.formView.urlInputView.sync()`.

---

## Hard solution

What we could do in the UI is 2-wDB, like 
1. Make `this.on( 'change:value', ( evt, propertyName, value ) => this.element.value = value || '' );` two-way
2. When the panel is shown, cache `formView.urlInputView.inputView.value`.
3. Let the user type. 
4. If OK is clicked, `formView.urlInputView.inputView.value` remains.
5. If cancel is clicked, `formView.urlInputView.inputView.value` is reverted to cached.

But the topic is risky as I pointed out in https://github.com/ckeditor/ckeditor5-ui/issues/110.

**Comment by Reinmar** [comment]
> like this.formView.urlInputView.inputView.sync() or even this.formView.urlInputView.sync().

Or `loadDataFrom( ... )` on the entire form? We may have more fields pretty soon.

**Comment by Reinmar** [comment]
> What we could do in the UI is 2-wDB, like

Sorry to repeat the same thing on and on, but I have no exp with 2-wDB but I only read bad things about it, even from developers who adopted e.g. Angular.

**Comment by szymonkups** [comment]
Issues of this kind should be fixed in a way @oleq showed in  https://github.com/ckeditor/ckeditor5-ui/issues/135#issuecomment-295800440 (Easy solution).
This is how it was resolved for link feature:

https://github.com/ckeditor/ckeditor5-link/blob/af224ba608a7d6672850ea3fc2421b8d2c49d0ee/src/link.js#L242-L247

In future we might need a helper which will update more fields at once.
