### ISSUE TITLE
Re–enable tooltips for disabled buttons

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui#140]
A followup of https://github.com/ckeditor/ckeditor5-ui/pull/120#issuecomment-270142106.

**Comment by Reinmar** [comment]
Isn't it done already?

**Comment by oleq** [comment]
Closed in https://github.com/ckeditor/ckeditor5-theme-lark/pull/60/commits/980832ddf0fc8b4dfe0aa026ebc751e87038167c.
