### ISSUE TITLE
Can't bind one attribute more than once

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#141]
UI throws an Error when I try to bind the same attribute more than once. Is this for technical reason or just our decision?

I know that I can use more than one property in `to()` method but for some reason, I need to make first binding inside one file and second in other. To do it I had to use `bind()` in first and `change` listener in second.

**Comment by oleq** [comment]
Could you provide a short sample of what you try to do? And which error?

**Comment by oskarwrobel** [comment]
Hm... I think I was trying to bind the same property to two different objects.
```
obj1.bind( 'sth' ).to( obj2 );
obj1.bind( 'sth' ).to( obj3 );
```
Exception:
```
observable-bind-rebind: Cannot bind the same attribute more that once.
```
I don't need this anymore but I had a reasonable reason to use it. To workaround this exception I had to listen on `change` event and update value manually.

**Comment by oleq** [comment]
Have I missed something or are you talking about `Observable#bind`, not `Template` bindings? If so, then this is the wrong repo ;-)

**Comment by oskarwrobel** [comment]
Oh, sorry. You are right. Moving to `ckeditor5-utils`
