### ISSUE TITLE
[Chrome] Tooltips are super blurry

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui#142]
![image](https://cloud.githubusercontent.com/assets/156149/21854424/fdb67b40-d81a-11e6-9860-dfd773b5c9a5.png)

Compare with:

![image](https://cloud.githubusercontent.com/assets/156149/21854439/0583ddc2-d81b-11e6-968b-ed76f7f20046.png)

I think that it may be related to non-integer value of `left` position of the tooltip... I don't know how it's positioned to 50% of the width of its parent, but perhaps Chrome isn't rounding this value internally?

**Comment by oleq** [comment]
I couldn't reproduce it but given my experience, I'm afraid it's a Chrome rendering issue with non-integer numbers. I happened to me a lot in other places too.

**Comment by Reinmar** [comment]
You're on 4K now, right? I can't reproduce it on retina. I'd need to check on my 2K monitor at work.

**Comment by oleq** [comment]
Have any updates on this issue, @Reinmar?

**Comment by Reinmar** [comment]
Yep, I checked on normal screens and they are blurry there. It happens also in the toolbar.

**Comment by Reinmar** [comment]
Idea – if we won't be able to find a font styling option for that we should change the sizes of buttons to some even numbers.

**Comment by oleq** [comment]
I'm afraid we're facing [this](https://stackoverflow.com/questions/31109299/css-transform-translate-50-50-makes-texts-blurry) problem here. I'll look for workarounds.

**Comment by dkonopka** [comment]
@oleq You have tried using `translate3d` instead of `translate`?

**Comment by oleq** [comment]
@dkonopka Yeah. I tried most of the fixes (translate3d, font-smoothing, etc.) and rounded the position of the balloon toolbar but to no avail. I noticed that it's a Webkit/Blink issue as it does not occur in Firefox. 

As it's not a critical issue (the feature is working), I'm for postponing it.

**Comment by Reinmar** [comment]
> As it's not a critical issue (the feature is working), I'm for postponing it.

Unfortunately, it's really visible so it isn't a neglectable issue either. If we can't find a solution, we should at least report it to Blink and Webkit.
