### ISSUE TITLE
escPressHandler should be replaced by KeystrokeHandler

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui#150]
In places like https://github.com/ckeditor/ckeditor5-image/blob/master/src/imagealternatetext/imagealternatetext.js#L105-L109 it should be replaced by an appropriate keystroke handler like https://github.com/ckeditor/ckeditor5-link/blob/master/src/link.js#L178-L184.

**Comment by Reinmar** [comment]
There's a ticket for the change in the image feature: https://github.com/ckeditor/ckeditor5-image/issues/40.

In this ticket we should remove the escPressHandler *and* think on how to refactor this code: https://github.com/ckeditor/ckeditor5-link/blob/63e70927751e3652b70375f23c1ff5bf5ba81723/src/link.js#L170-L192. It'll repeat in the image package as well. Perhaps it should be a part of https://github.com/ckeditor/ckeditor5-ui/issues/134.

**Comment by oskarwrobel** [comment]
`escPressHandler` is used nowhere. We can remove it.
