### ISSUE TITLE
Toolbar sticking and unsticking with lag

### ISSUE THREAD

**Issue by m-kr** [ckeditor/ckeditor5-ui#159]
Toolbar's state changes from sticky to static and vice versa with a little lag. I think that toolbar should change positioning without any timeout.

![sticky-toolbar](https://cloud.githubusercontent.com/assets/8529247/23259953/e62af6be-f9cf-11e6-82cf-07a37d56fdfb.gif)

**Comment by m-kr** [comment]
Yep, some of Chrome extension causes this issue, on *incognito* mode, toolbar changes position without any lags.

**Comment by Reinmar** [comment]
Interesting, could you perhaps test which?

**Comment by m-kr** [comment]
It's [Grammarly](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen?hl=en), this problem exists after text changing.

**Comment by Reinmar** [comment]
Hm... ;/ Not good.
