### ISSUE TITLE
Custom place for body collection

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#171]
Now `body` collection is injected to DOM `body` element: https://github.com/ckeditor/ckeditor5-ui/blob/master/src/editorui/editoruiview.js#L82 and this should work fine for most of `CKE5` use cases.

But what if someone will want to override this class and inject this collection to other than body scrollable container? Then Position util will return incorrect values because it gets scroll value only from `window` object https://github.com/ckeditor/ckeditor5-utils/blob/master/src/dom/position.js#L217 and it's not configurable.

WDYT to make this configurable somehow?

**Comment by oleq** [comment]
This could easily become a config option.

**Comment by Reinmar** [comment]
There was somewhere discussion with @Comandeer regarding the fact that we don't need to use the body collection. I think that it was related to web components. The problem we had there was that if you want to ship CKEditor as a web component it should not leak its UI elements outside of the element in which it's defined. Hence, the body collection would be a problem. However, @Comandeer pointed out that using a bit different approach to styling these floating elements we should be fine. Also, we talked about the hidden overflow problem of the container... Can someone find it? :D

**Comment by Reinmar** [comment]
BTW, this is not a bug IMO, but a feature of enhancement.

**Comment by oskarwrobel** [comment]
We can start from making `Position` util configurable. No matter if we will get rid of `body` collection or not the Position util needs to have configurable container element.

**Comment by oskarwrobel** [comment]
When container element will become a config option of `getOptimalPosition()` then we will need to make possible to provide this option. `getOptimalPosition()` is called by `BalloonPanelView#atachTo()` so we can add the same option to `atachTo()` and inside `attachTo` provide this option to `getOptimalPosition`. This will work for every custom balloon panel but won't work for link balloon because link calls `attachTo()` internally.

**Comment by oleq** [comment]
Did https://github.com/ckeditor/ckeditor5-utils/issues/139 resolve this issue?

**Comment by oskarwrobel** [comment]
Yes. I'm closing it.

**Comment by tuomassalo** [comment]
I'd like to reopen this case.

I'm running a web app that has editor panes that come and go - and their styling varies. I'm trying to tweak the styles and visibility lifecycle of the toolbars accordingly. For that purpose, I would find it handy that I could set where in the DOM the editors add their toolbars.

For the record, at the moment I achieve this in a custom build by monkey-patching this line: https://github.com/ckeditor/ckeditor5-ui/blob/102e25aaab48eb3798b023c244cd19ac6321cacc/src/editorui/editoruiview.js#L85

**Comment by oleq** [comment]
@tuomassalo You can access the "body" collection container during editor's life cycle using `editor.ui.view._bodyCollectionContainer` and move it somewhere else

```js
ClassicEditor
	.create( ..., {
		// ...
	} )
	.then( editor => {
		window.editor = editor;

		someContainer.appendChild( editor.ui.view._bodyCollectionContainer );
	} )
	.catch( err => {
		console.error( err );
	} );

```

In fact, this issue is a piece of a larger problem now: [running the editor in the shadow DOM](https://github.com/ckeditor/ckeditor5-engine/issues/692).

**Comment by Reinmar** [comment]
We can track (and eventually resolve) this subissue separately, though. Otherwise, it'll get lost in the shadow DOM thread.

We have at least two reasons now (shadow DOM and @tuomassalo's use case) to make the body collection configurable. That sounds like a valid issue, therefore.

PS @tuomassalo could you share a bit more details why you need to customise it? I'm not sure that I understand your scenario.
