### ISSUE TITLE
Improve ContextualBalloon manual test

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#185]
Follow-up: https://github.com/ckeditor/ckeditor5-ui/issues/134

After `ContextualBalloon` will be integrated with `Link` or `Image` and `ContextualToolbar` component will be introduced we can simplify `ContextualToolbar` manual test using above plugins/components.

**Comment by oleq** [comment]
Is the issue still valid?

>  we can simplify ContextualToolbar manual test using above plugins/components.

Did you mean `ContextualBalloon` manual test?

**Comment by oskarwrobel** [comment]
Yes, `ContextualBalloon` manual test. I think this issue is still valid because `CB` manual test is quite complex.
