### ISSUE TITLE
Component to manage a stack of child views

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#186]
Follow-up: #134

This is about extracting core part of the `ContextualBalloon` and separate from the view.
See: https://github.com/ckeditor/ckeditor5-ui/pull/177#discussion_r109635520

**Comment by oleq** [comment]
Let's find out if there will be more use cases for the component before we start refactoring.

**Comment by Reinmar** [comment]
Sounds like... just happened?

**Comment by oskarwrobel** [comment]
> Sounds like... just happened?

Not exactly, but at the moment we don't need to extract this part of the code. `ContextualBalloon` has changed so much past last 2 years so this issue may not have sense anymore.
