### ISSUE TITLE
Position of balloons should be updated on external changes

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#198]
The first user clicks on link element and sees balloon panel attached to this element. The second user types something before this link element. The result: link element is moving but attached balloon stays at the same position.

**Comment by oleq** [comment]
I think it's enough to call [`pin()`](https://github.com/ckeditor/ckeditor5-ui/pull/197) on ` editor.editing.view#render` and it's up to the features using the `BalloonPanelView` to do this. The UI library should not be aware of the engine and vice-versa unless we'd like to deal with some very cumbersome dependencies in the project.

**Comment by oskarwrobel** [comment]
> it's up to the features using the BalloonPanelView to do this.

👍
