### ISSUE TITLE
BalloonPanelView should not be focusable

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui#206]
![kapture 2017-04-19 at 9 09 23](https://cloud.githubusercontent.com/assets/1099479/25167475/e940ac0a-24df-11e7-968b-cdcf8527ef1c.gif)

Because of that we end up with problems like https://github.com/ckeditor/ckeditor5-link/issues/90. It's probably just a matter of using the `@mixin ck-unselectable` in SASS.

**Comment by Reinmar** [comment]
Isn't that CSS supported by Chrome only?

**Comment by oleq** [comment]
Nope. It's [supported](http://caniuse.com/#feat=user-select-none) by almost every major web browser.

**Comment by Reinmar** [comment]
And why is the balloon focusable in the first place?

**Comment by oleq** [comment]
Most certainly because the author (me) has never considered this thing becoming a problem and obviously was wrong ;-)

**Comment by Reinmar** [comment]
There must've been some reason. I even recall there was something... But I don't remember what and whether this is still any relevant. Hopefully not... but I remember that CKE4's dialogs were also focusable.

**Comment by oleq** [comment]
> but I remember that CKE4's dialogs were also focusable.

They aren't. Or at least, they don't look like they accept focus.

**Comment by Reinmar** [comment]
> They aren't. Or at least, they don't look like they accept focus.

That's odd. I was nearly sure they were. So... I'll better stop confusing you :D

**Comment by oskarwrobel** [comment]
```
// Make this element `focusable` to be available for adding to FocusTracker.
tabindex: -1
```

**Comment by oleq** [comment]
Maybe we don't need it anymore, hard to tell.
