### ISSUE TITLE
Keyboard support for the ContextualToolbar

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#207]
Follow-up: https://github.com/ckeditor/ckeditor5-ui/issues/182

When the `ContextualToolbar` is opened and editable is focused then <kbd>Tab</kbd> should focus `ToolbarView` inside `ContextualToolbar` and <kbd>Esc</kbd> should blur it.

**Comment by oleq** [comment]
> and Esc should blur it

O maybe hide it? I'd need to see it in action but more often than not users expect floating stuff to disappear once <kbd>Esc</kbd> is pressed.

**Comment by oleq** [comment]
Doesn't it duplicate with https://github.com/ckeditor/ckeditor5-editor-balloon-toolbar/issues/3?
