### ISSUE TITLE
[Edge] Template.apply() throws "Object doesn't support property or method 'matches'"

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui#214]
The reason is that Edge still doesn't support [`Element#matches()`](https://developer.mozilla.org/en/docs/Web/API/Element/matches).

**Comment by Reinmar** [comment]
[The next version of Edge](https://github.com/ckeditor/ckeditor5-utils/issues/152#issuecomment-296692325) should bring support for `matches()` so let's wait.

**Comment by oleq** [comment]
I ran all ckeditor5-ui tests in Edge 15.15063 and the only one failing is not related to `domElement.matches()`.
