### ISSUE TITLE
[Safari] Toolbar's icon label is covered by browser's label

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-ui#245]
## Steps to reproduce
1. Open a sample.
2. Hover some toolbar item and wait few seconds.

## Current result
Editor's label is covered by browser's label.

## Screenshot
![screen2](https://cloud.githubusercontent.com/assets/20988892/26832042/6eadfe88-4ace-11e7-88a0-72511467c194.png)

## Other information
OS: MacOS X
Browser: Safari
Release: 0.10.0

**Comment by oleq** [comment]
It looks like Safari creates tooltips for `<title>` tag inside `<svg>`. All we need to do is clean up our icon set.

**Comment by szymonkups** [comment]
I've merged cleaned up svg icons in https://github.com/ckeditor/ckeditor5/issues/474 and the issue is solved. @Mgsy could you verify it again?

**Comment by Mgsy** [comment]
@szymonkups, everything works fine, thanks. It's fixed, so I'm closing this one.
