### ISSUE TITLE
[Chrome, Safari] Selection dragged from a dropdown item shouldn't move outside of a list

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-ui#247]
## Steps to reproduce
1. Open a sample.
2. Open a dropdown list. 
3. Start a selection from a dropdown item and move it on a paragraph.

## Current result
- **Chrome**: Caret changes position with every mouse move.
- **Safari**: Mouse movement creates a selection on a paragraph. 

## Expected result
Selection shouldn't move outside of a dropdown list.

## GIF
*Chrome*
![bug](https://user-images.githubusercontent.com/20988892/26877055-ff86d8de-4b88-11e7-8df6-60d6faf534b7.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Safari
Release: 0.10.0

**Comment by Reinmar** [comment]
I think that there's no "expected result" here. It's nothing that the user may do by a coincidence so I don't think we need to care what happens. Especially that a fix doesn't sound trivial.

**Comment by fredck** [comment]
Isn't it a simple UI fix, by disallowing selection and dragging in the dropdown?

**Comment by oleq** [comment]
@fredck Nope. Selection and dragging have been disabled in dropdown since https://github.com/ckeditor/ckeditor5-ui/issues/228. 

To deal with this issue, we'd need to disable selection/drag in editable when the drop down is open which is not quite as easy as it seems. The dropdown doesn't know about the environment and that includes the editable. TBH, I'm unable to come up with any quick idea how to deal with this issue.

**Comment by fredck** [comment]
@oleq, is there any chance that the fix for #228 was not appropriate, making the element "transparent" for selection? Could [user-select](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) be an alternative that would solve the problem?

**Comment by oleq** [comment]
`user-select` has been [disabled](https://github.com/ckeditor/ckeditor5-ui/blob/master/theme/components/list.scss#L5) on the `.ck-list` for a long time. The same for drop-down panel, which inherits this behavior from the toolbar. 

Please note that in this issue, the selection in the editable starts to move once it **exists** the dropdown, not before.

**Comment by Mgsy** [comment]
I'm not able to reproduce it anymore.
