### ISSUE TITLE
Resolve the matter of UI resizing for BoxedEditorUIView

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui#25]
`BoxedEditorUI` defines observable `width` and `height` attributes. They should be bound with the logic of the `View` to resize editor via `editor.ui.[width | height]`. It 

A followup of https://github.com/ckeditor/ckeditor5-ui/issues/22.

**Comment by Reinmar** [comment]
I'm not entirely sure we need this. So far you can easily resize editor using CSS. I implemented `editorUI#width|height` as a part of the prototype that we have in manual tests. It doesn't make that much sense though.

**Comment by oleq** [comment]
Alright, let's get rid of [those orphans](https://github.com/ckeditor/ckeditor5-ui/blob/master/src/editorui/boxed/boxededitoruiview.js#L32-L46) then because they suggest developers this is actually something that works and we know this is not true. A misleading piece of code, that's all.

**Comment by Reinmar** [comment]
PS. If you're looking for how to set CKEditor 5's height and width, then the news is that:

* There's no `config.height` and `config.width` like in CKEditor 4.
* You can just use CSS.

To set the height:

```css
.ck-editor__editable {
    min-height: 400px;

    /* or: */
    height: 400px;
}
```

To set the width:

```cs
.ck-editor {
    width: 400px;
}
```
