### ISSUE TITLE
What should DropdownView interface look like?

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui#250]
[The actual documentation of the view is misleading](https://github.com/ckeditor/ckeditor5-ui/issues/249) and the only actual observable of the view is `#isOpen`. All the rest like `#isEnabled`, `#isOn` etc. are `view#buttonView` attributes. 

On one hand, it's not a big deal – the feature (controller) binds data from the editor to the dropdown, not the other way around, so these attributes are not used outside the view that often. 

On the other hand, it looks weird that the actual state of the `DropdownView` instance is maintained in one of its children. And as I talk about `#isEnabled`, it feels natural to me that the interface it should be `DropdownView#isEnabled`, not `DropdownView.buttonView#isEnabled`, right?

Should we do anything about it or it's just me? (cc @Reinmar @szymonkups @oskarwrobel)

**Comment by oskarwrobel** [comment]
> On the other hand, it looks weird that the actual state of the DropdownView instance is maintained in one of its children. And as I talk about #isEnabled, it feels natural to me that the interface it should be DropdownView#isEnabled, not DropdownView.buttonView#isEnabled, right?

Yep, It's weird.  `DropdownView` should provide the interface. We have a similar scenario with `LabeledInputView` where we bound child attributes to the parent view https://github.com/ckeditor/ckeditor5-ui/blob/master/src/labeledinput/labeledinputview.js#L101

**Comment by Reinmar** [comment]
I'm not sure about this.

Perhaps I'm overthinking this but it's a bit like the inheritance vs composition problem.

What's a dropdown? It's a composition of a button and panel with some content. Should all properties of dropdown's children be also properties of the dropdown itself? I don't think so.

Let's take a different example. A link form. It consists of a couple of inputs and buttons. Should properties of all of them be exposed on the link form? I don't think so.

So what should be exposed on parent components? I think that as little as possible. I feel that as little as possible (i.e. usually nothing) in typical composition cases. In cases which are closer to inheritance (could be labelled view) we could proxy the properties to the parent. But that means a stronger dependency on the API of the child components and hence a tighter coupling.

Back to the dropdown view – what should it expose? Ideally – only the thing which it adds to the button+panel pair. Are there really any reasons to expose more?

... and I'll try to answer that question too :D Yes, there could be. We might go the way that e.g. a toolbar assumes some common interface of its children. This could be e.g. useful to implement <kbd>Tab</kbd> navigation through it if toolbar should skip e.g. disabled items (which is not really the case AFAIR).

Of course, assuming too much regarding the interface of toolbar items may make it hard to implement some special toolbar compatible components (think for instance – a link form which appears in the toolbar directly).

So far, AFAIK, the focus navigation is the only thing which needs some interface from toolbar items (namely – the focusable fields). Is that true, @oleq? Unless we have more needs like this, I'd really avoid exposing too much on parent components.

**Comment by oskarwrobel** [comment]
🤔

**Comment by oleq** [comment]
> So far, AFAIK, the focus navigation is the only thing which needs some interface from toolbar items (namely – the focusable fields). Is that true, @oleq? Unless we have more needs like this, I'd really avoid exposing too much on parent components.

Well, yes. The only thing that `ToolbarView` knows about its children is `child#element` (to actually insert and manage it in DOM) and `child#focus()` method (to enable `FocusCycler` – keyboard navigation).

TBH, when I first read your comment I was like _WAT_ but now I understand your point of view. Still, I'm not totally convinced about it. Let's talk about:

> Let's take a different example. A link form. It consists of a couple of inputs and buttons. Should properties of all of them be exposed on the link form? I don't think so.

How would one disable the entire form consisting of 30 inputs? `FormView#isEnabled` is the necessary public API in such situation.

> What's a dropdown? It's a composition of a button and panel with some content. Should all properties of dropdown's children be also properties of the dropdown itself? I don't think so.

All properties, no. But some, yes. Think about DX – developers don't care about the composition and sub–components, all they need is to insert and control the `DropdownView` to solve their problem. They will expect key properties/attributes to exist at `DropdownView#foo` level, like in other popular libraries. 

If we stick to `DropdownView.buttonView#isEnabled`, and at some point in the future we either
* replace the `buttonView` with some other view, which has no such attribute,
* introduce new parts to the component which also have `#isEnabled` 

we'll break existing implementations created by developers and bring nothing but confustion. All of this because we use the "internal" API of the component instead of the public `DropdownView#isEnabled`, which can mask and hide whatever happens inside.

BTW: We already have `#isOpen`, which then controls `DropdownView.panelView#isVisible`. What if lots of developers already used `DropdownView.panelView#isVisible` instead and we are forced to refactor the component to use some other panel with other attribute? Such refactoring should be seamless, they shouldn't be bothered.

**Comment by oskarwrobel** [comment]
> If we stick to DropdownView.buttonView#isEnabled, and at some point in the future we either
>
> - replace the buttonView with some other view, which has no such attribute,
> - introduce new parts to the component which also have #isEnabled
>
> we'll break existing implementations created by developers and bring nothing but confustion. All of this because we use the "internal" API of the component instead of the public DropdownView#isEnabled, which can mask and hide whatever happens inside.

This is exactly what I was thinking about.

**Comment by Reinmar** [comment]
Don't get me wrong guys – I do agree that it may make sense to expose some component API. But it should be minimal and base on careful reasoning and real needs. `isEnabled` is a good example of that. It makes sense for the entire dropdown to be disabled. 



> replace the buttonView with some other view, which has no such attribute,

`DropdownView` will always have the `buttonView` property – whatever kind of button-like component you'll put there it always should be under this property.

In other words – `DV#buttonView` is the public API of `DV`. Whatever you change in this API, you introduce breaking changes.

> introduce new parts to the component which also have #isEnabled

Then it will be breaking changes once again, unless the changes will stay internal to DV. 

So, from this perspective `DV.buttonView.isEnabled` is really ok. So do `label`, `icon` and other button-related properties.

In the same way as one needs to expect that `editor.document.*` is a public API of the editor itself. You don't put any of the `DataController`, `EditingController`, `Document`, `EditorUI` methods and properties on the `Editor` itself unless for DX reasons (`Editor#execute()`, `Editor#setData()`, etc.).

So, I still think that the only reason for exposing anything on `DV` is DX and meeting common interfaces.

**Comment by Reinmar** [comment]
One more thing – we need to be extremely cautious with situations like exposing stuff like `isEnabled` because developers are used to the fact that it's available on the button. I guess the binding (change flow) will be `DV.isEnabled -> button.isEnabled` but the question is who should create it. The `DV` constructor or the `createDropdown` function?

If it's the constructor, then whoever will be creating `DV` instance in whatever way, the binding will be created. And since you can pass your own button instance to `DV` will you bind its `isEnabled` to your command? How can you remember and know that `DV` has its own `isEnabled`?

This can be documented of course, but I have mixed feelings regarding this because `DV`'s constructor accepts button and panel instances so it should expect that they have all their properties set and controlled already.

**Comment by oleq** [comment]
I think the discussion is outdated, especially considering the latest refactoring of the drop-down family https://github.com/ckeditor/ckeditor5-ui/issues/356. The component [API](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/api/module_ui_dropdown_dropdownview-DropdownView.html) can be found in docs.
