### ISSUE TITLE
clickOutsideHandler and multiple elements

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-ui#261]
I want to use `clickOutsideHandler` but pass multiple elements as "inside", so clicking on any of these elements will not be considered as clicking "outside". 

On solution would be to make it possible to pass multiple `contextElement` and check all of them if they contain `target`.

Another would be to pass `evt` and `target` to the `activator` function to make it possible to check target in the activator.

**Comment by oleq** [comment]
I'm for it. OTOH, as a workaround you can call `clickOutsideHandler` multiple times and it should work fine, right?

**Comment by pjasiun** [comment]
No. Then the action from the `clickOutsideHandler` will be executed on all elements. It will be (!a || !b), what I need is (!(a || b)) or (!a && !b).

**Comment by pjasiun** [comment]
In my case, I want to prevent `clickOutsideHandler` action on both panel and button which opens this panel. Otherwise, I am not able to close the panel by clicking on the button, because when I click on it when the panel is open `clickOutsideHandler` hides the panel and then click action is executed and the panel is re-opened. I want to prevent `clickOutsideHandler` on the button so the button can hide the panel separately.

**Comment by oleq** [comment]
OK, now I got it. Thanks.
