### ISSUE TITLE
Implement ContextualBalloon#clear method

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui#272]
It's needed by https://github.com/ckeditor/ckeditor5-image/issues/96 to get rid of all view in some situations. `CB#remove` is not so pretty and efficient because it means removing the `#visibleView` in a loop until it's `null`, and each time it modifies the DOM.

**Comment by oskarwrobel** [comment]
This API method is dangerous. Only specific plugin should be able to remove its view. When some plugin will remove all views from the stack the rest of the plugins which view was in the stack won't know it (won't clear its listeners etc.).

**Comment by oleq** [comment]
How to we solve the problem of https://github.com/ckeditor/ckeditor5-image/issues/96 then?

There's an `ImageBalloon` built on top of `ContextualBalloon`. Both `ImageToolbar` and `ImageTextAlt` use it display their UI. It aggregates the common stuff like 
* balloon position, which is the same for both plugins, 
* `#render` listener that re–positions the balloon 
* and `focusTracker` integration which hides the balloon, when editor lost focus.

How to implement the last one without duplicating the code in `ImageToolbar` and `ImageTextAlt`?

**Comment by oskarwrobel** [comment]
I don't understand how clearing the stack helps with it.

**Comment by oleq** [comment]
Take a look on https://github.com/ckeditor/ckeditor5-image/pull/125/files#diff-aa59e0ba941feab77c95e20a9e6357f9R91.

**Comment by oskarwrobel** [comment]
I'm still not sure if I understand.
If ImageBalloon wants to be removed from CB on UI blur it should remove only its view not force to remove all views from the stack.

**Comment by oleq** [comment]
> If ImageBalloon wants to be removed from CB on UI blur it should remove only its view not force to remove all views from the stack.

```js
class ImageBalloon extends ContextualBalloon 
```

`IB` is essentially an instance of `CB` that implements unified 
* positioning
* listening to `#render`
* reacting to focus loss

for all UIs in the `Image` package.

I don't want to duplicate the code and handle editor's blur both in `ImageToolbar` and `ImageTextAlt` (they would remove their respective views from `IB`).

**Comment by oskarwrobel** [comment]
So if `ImageBalloon` extends CB you can implement `clear()` method in ImageBalloon.

**Comment by oleq** [comment]
The issue is no longer relevant. See https://github.com/ckeditor/ckeditor5-image/pull/125#issuecomment-315330696.
