### ISSUE TITLE
Make clickOutsideHandler use mousedown instead of mouseup

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui#281]
It looks like the wrong event makes a difference:
* https://github.com/ckeditor/ckeditor5-image/issues/128
* https://github.com/ckeditor/ckeditor5-image/issues/129
* https://github.com/ckeditor/ckeditor5-link/issues/118

But why we chose `mouseup` it the first place? (cc @Reinmar)

**Comment by oleq** [comment]
The event was changed to `mouseup` in this [refactoring](https://github.com/ckeditor/ckeditor5-ui-default/commit/33d070645c112330c2e38559dd478a0891acaeb2#diff-0192a2de091503bee4ee9d7929eb6f63). @oskarwrobel, do you remember why?

**Comment by oskarwrobel** [comment]
I don't remember. There was something related to clicking on toolbar buttons while LinkBalloon is opened but I'm not sure if this was a reason for this change.
