### ISSUE TITLE
Cannot easily turn off a tooltip once added

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#283]
How to easily torn off a tooltip once added?

Now when tooltip value is set as `''` empty tooltip appears.

![image](https://user-images.githubusercontent.com/1057056/28872541-f246c7e2-7789-11e7-88ee-924feda43235.png)

**Comment by oskarwrobel** [comment]
I think there is also a problem with adding tooltip to button which was created without a tooltip.
E.g button was initialized without a tooltip, but you want to show a tooltip when button will be disabled.

**Comment by oleq** [comment]
I think that the tooltip should always be added to the button in case developers wants to enable it after the button is initialized. Then the presence of the `#tooltip` text should control `.ck-hidden` class of the tooltip, so it never shows up when empty.
