### ISSUE TITLE
The link balloon does not respect the position of the ContexualToolbar 

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#285]
## Now is:

![aug-03-2017 12-21-19](https://user-images.githubusercontent.com/1057056/28917568-63e5118a-7846-11e7-98ef-558f0f5a08b7.gif)

## Expected result:

![aug-03-2017 12-28-25](https://user-images.githubusercontent.com/1057056/28917804-3b4c9efe-7847-11e7-87c8-05074e7b8c30.gif)

**Comment by oskarwrobel** [comment]
This might be related: https://github.com/ckeditor/ckeditor5-ui/issues/178.

**Comment by oskarwrobel** [comment]
Ok, fix for this issue is very easy. But we have a problem with integration tests for `ContextualBalloon`, `Contextualtoolbar` and `Link`. We test separately `CB` + `Link` and `CB` + `CT` but we don't test all of them together.

`ContextualBalloon` manual test looks like a good place to test integration with all plugins which use `CB`. We already have a MT for `CB` but it was written when there was no plugin using CB and is really complex and I have a feeling we don't use it at all.

I'm going to refactor MT of `CB` to make them test CB + CT + Link (including tests for external changes). We already have a task for such refactoring #185.

**Comment by oskarwrobel** [comment]
@oleq does your fix works fine with document external changes?

**Comment by oskarwrobel** [comment]
This is my fix

```diff
diff --git a/src/panel/balloon/contextualballoon.js b/src/panel/balloon/contextualballoon.js
index 455c9b2..dc900d0 100644
--- a/src/panel/balloon/contextualballoon.js
+++ b/src/panel/balloon/contextualballoon.js
@@ -159,14 +159,14 @@ export default class ContextualBalloon extends Plugin {
        }

        /**
-        * Updates the position of the balloon panel according to the given position data
-        * or position data of the first view in the stack.
+        * Updates the position of the balloon using position data of the first visible view in the stack.
+        * When new position data is given then position data of currently visible panel will be updated.
         *
         * @param {module:utils/dom/position~Options} [position] position options.
         */
        updatePosition( position ) {
                if ( position ) {
-                       this._stack.values().next().value.position = position;
+                       this._stack.get( this.visibleView ).position = position;
                }
```

**Comment by oleq** [comment]
LGTM. I need to see in action first, though.

**Comment by Reinmar** [comment]
Just saying – is this really needed now? This seems like it12+, not a critical thing.

**Comment by Reinmar** [comment]
In fact, I'd be far from marking it as a bug. It's more of an enhancement we can make.

**Comment by oskarwrobel** [comment]
It's a regression.

**Comment by Reinmar** [comment]
Haha :D I didn't know that it worked already. Then it's a bug :D  Although, still not critical ;)

**Comment by oskarwrobel** [comment]
Fix for this seems to be really simple:
```diff
-                       this._stack.values().next().value.position = position;
+                       this._stack.get( this.visibleView ).position = position;
```
