### ISSUE TITLE
Content inside BalloonPanelView is not selectable

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#294]
This is probably OK when BPV is used for showing form but when you want to show e.g. notifications it should be possible to select and copy text.

This is probably the reason why BPV is unselectable https://github.com/ckeditor/ckeditor5-ui/issues/243.

**Comment by oleq** [comment]
It also breaks this one https://github.com/ckeditor/ckeditor5/issues/498.

**Comment by oskarwrobel** [comment]
I see that BPV is unselectable because:
- https://github.com/ckeditor/ckeditor5-link/issues/126
- https://github.com/ckeditor/ckeditor5-link/issues/90
- https://github.com/ckeditor/ckeditor5-ui/issues/228

I removed unselectable "feature" and I think I can't reproduce first two. I'm not sure about the third one but I think we can fix it only for dropdown not for the entire BPV.

**Comment by oleq** [comment]
The third one is not about `BalloonPanelView` so it's beyond the scope of this issue.

As for the first two, we **have to** understand why removing this line https://github.com/ckeditor/ckeditor5-ui/blob/master/src/panel/balloon/balloonpanelview.js#L140 does not cause any regression.
