### ISSUE TITLE
Create StickyPanelView

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#297]
We already have a `StickyToolbarView` that extends `ToolbarView`. I'm thinking about creating a separate view instead, like `BPV` with content collection and add `ToolbarView` as a child. This will make possible to easily create any sticky bar not only sticky toolbar.

**Comment by oleq** [comment]
Yes, this makes sense. 

OTOH, I had [an idea](https://github.com/ckeditor/ckeditor5-ui/issues/202) to use `BPV` to code `STV`. OTOH again, we got to make sure cons don't overweight pros in such approach and I'm not so sure about it. So maybe let's postpone this issue, WDYT?

And finally, there's the issue about jittering https://github.com/ckeditor/ckeditor5-editor-inline/issues/22. I think it's time to consider it now.

**Comment by fredck** [comment]
Just wanted to leave here a mention regarding the name. If you guys proceed with it, consider something like "StickySpaceView", "StickyComponentView", even "StickyView" or whatever, but not use "Bar" in it.

**Comment by oleq** [comment]
I think `StickyPanelView` is the right name as it corresponds with `BalloonPanelView`.

**Comment by oskarwrobel** [comment]
Ok, so let's try with new `StickyPanelView` component.
