### ISSUE TITLE
[Tests] Broken image toolbar manual test

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui#302]
http://localhost:8125/ckeditor5-ui/tests/manual/imagetoolbar/imagetoolbar.html shows errors and won't start.

**Comment by oleq** [comment]
While fixing this test I noticed that... it's no longer necessary. The functionality has been replaced by `ContextualBalloon` and `ContextualToolbar`
* http://localhost:8125/ckeditor5-ui/tests/manual/contextualballoon/contextualballoon.html
* http://localhost:8125/ckeditor5-ui/tests/manual/contextualtoolbar/contextualtoolbar.html
* http://localhost:8125/ckeditor5-ui/tests/manual/tickets/170/1.html

We no longer use `BalloonPanelView#pin` to implement such features and I think maintaining this test is pointless. WDYT @oskarwrobel?

**Comment by oskarwrobel** [comment]
Yes, I think this test makes no sense anymore. But I can't find any `ImageToolbar` MT testing how it works now. I mean how`ImageToolbar` works using `ContextualBalloon`. We have [MT](http://localhost:8125/ckeditor5-image/tests/manual/tickets/106/1.html) for `ImageTextAlternative` balloon but we don't have a similar test for `ImageToolbar`.

Actually, we are able to test `ImageToolbar` using `ImageTextAlternative` test.
