### ISSUE TITLE
[Chrome] Input autocomplete in balloon panels is not correctly repositioned

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#307]
It should be repositioned or disappear but its position is fixed.

![sep-20-2017 20-25-12](https://user-images.githubusercontent.com/1057056/30660623-cd823534-9e41-11e7-8aff-a34cf258b0e8.gif)

**Comment by oleq** [comment]
[More on the topic](https://stackoverflow.com/questions/43646805/wrong-input-autocompletion-position-on-scroll-chrome).

**Comment by Mgsy** [comment]
Right now the autocomplete box closes on scroll, so this one is no longer a valid issue.
