### ISSUE TITLE
Get rid of the Model class

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui#314]
It used to be a thing until views became observables. ATM the only [usage](https://github.com/ckeditor/ckeditor5-heading/blob/master/src/heading.js#L56-L60) of the Model class is in the heading feature and in a couple of tests related to `createListDropdown` helper. 

I think maintaining this class makes little sense because any kind of observable can handle the task and the scope is very, very limited.

cc @Reinmar, @oskarwrobel

**Comment by Reinmar** [comment]
I'm removing this from iteration 12. Not sure what it does here.

**Comment by oleq** [comment]
When working on https://github.com/ckeditor/ckeditor5-ui/issues/262 I found out removing this class is not as easy as I thought. It could be removed but then we would need to do something like
```js
Foo = class extends Observable {}
```
(or similar) in many places like [this one](https://github.com/ckeditor/ckeditor5-heading/blob/master/src/heading.js#L56) (propagated [here](https://github.com/ckeditor/ckeditor5-ui/blob/master/src/dropdown/list/createlistdropdown.js#L58-L65)) to create an intermediate container for observable attributes, which is super ugly. 

If you have any better idea how to do this without `Model`, I'm open to suggestions.

**Comment by Reinmar** [comment]
OK, we use it so let's keep it.
