### ISSUE TITLE
The balloon closes after focusing the input in read-only mode

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-ui#328]
## Steps to reproduce
1. Create new link.
2. Enter `read-only` mode.
3. Open the link balloon.
4. Focus the input.

## Current result
The link balloon closes. 

## Notes
It works fine on Firefox.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31715084-bde5a6d4-b402-11e7-9ee9-564fc573cdf3.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Safari, Edge, Opera
Release: 1.0.0-Alpha1

**Comment by Mgsy** [comment]
It doesn't occur when the input is empty and contains only the placeholder.

![bug_cke5](https://user-images.githubusercontent.com/20988892/31717317-a9faa63e-b40b-11e7-8368-d13c0e1ffbf4.gif)

**Comment by oleq** [comment]
This issue should be submitted in ckeditor5-link repo.

**Comment by Mgsy** [comment]
> This issue should be submitted in ckeditor5-link repo.

Thanks, I'm moving it to the proper repo - https://github.com/ckeditor/ckeditor5-link/issues/156.
