### ISSUE TITLE
Sidebar is off by 1 pixel on the bottom

### ISSUE THREAD

**Issue by vladikoff** [ckeditor/ckeditor5-ui#355]
This is true for the `-heading` dropdown module, the `basic-styles` icons (bold, italic) are also off by `~1px` on the bottom:

![uneven](https://user-images.githubusercontent.com/128755/34174241-49e3742e-e4c6-11e7-9a6b-bf9002b5bee7.png)

Not sure if this by design or needs to be fixed...

**Comment by oleq** [comment]
I couldn't reproduce it on master (Chrome 63.0.3239.84, Retina on Mac).
<img width="401" alt="screen shot 2017-12-20 at 10 13 40" src="https://user-images.githubusercontent.com/1099479/34199562-7cf33cb6-e56e-11e7-9ff6-860b2dd78b11.png">

**Comment by oleq** [comment]
The issue boils down to https://github.com/ckeditor/ckeditor5-theme-lark/issues/145.
