### ISSUE TITLE
Change which classes determines dropdown button visual styles

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-ui#358]
It might be changed by #356 but I think it keeps up with a direction of changes in that ticket.

Right now every "dropdown button" in toolbar gets border and bakcground (like the heading dropdown) and adding type of dropdowns required to add exceptions to that CSS rules in theme.

I think that's better to not add those visual styles to dropdown buttons but instead to only style those "withText" (as in heading dropdown case).

**Comment by oleq** [comment]
OK, in other words, what you propose in https://github.com/ckeditor/ckeditor5-ui/compare/t/ckeditor5-font/4 is hoisting dropdown button's `.ck-button_with-text` class to parent dropdow's class (`.ck-dropdown__withtext`)?

**Comment by jodator** [comment]
Hmm I might missed that `ck-button_with-text` then when looking up the rendered toolbar. Or I wasn't sure how to properly change lark CSS for what I wanted to achieve...

**Comment by jodator** [comment]
@oleq I think that you're right. I think that we can just use existing `ck-button_with-text` instead what I've proposed. I'll check this and I'll update both PR (UI/theme-lark).

**Comment by jodator** [comment]
OK this one can be closed. I'll create a ticket for theme-lark only.

**Comment by jodator** [comment]
OK. I've moved the solution to theme-lark only: https://github.com/ckeditor/ckeditor5-theme-lark/issues/122.
