### ISSUE TITLE
EditorButtonModel#command to create button-command binding

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui#36]
This could be automated:

``` js
model.bind( 'isEnabled' ).to( command, 'isEnabled' );

this.listenTo( model, 'execute', () => editor.execute( name ) );
```

Note: I intentionally called this model `EditorButtonModel` not `ButtonModel` to indicate that the general button model should rather not know about such things.

**Comment by oleq** [comment]
I suppose 

```
this.listenTo( model, 'execute', () => editor.execute( name ) );
```

part could be simplified by [event delegation](https://github.com/ckeditor/ckeditor5-utils/issues/50) implemented in iteration 2 like

```
model.delegate( 'execute' ).to( editor ); // ???
```

if `editor` handled `execute` events with `editor.execute( name )` callback somehow.

**Comment by oleq** [comment]
No longer valid since https://github.com/ckeditor/ckeditor5-ui/issues/95.
