### ISSUE TITLE
SplitButton looks odd when it's on

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui#379]
![image](https://user-images.githubusercontent.com/156149/37216797-04ee1eca-23bc-11e8-916f-a6f5c49176a0.png)

It's looking a bit odd when it's "cut" like this. I know that the arrow cannot be on with the button because the arrow should be on when the panel is opened, but perhaps we could add border-radius to the top-right and bottom-right corners of the button when only the button is on? This would need to be somehow reverted when the whole thing is hovered or the panel is opened.

**Comment by oleq** [comment]
I think Google Docs is a good example that it doesn't look that weird after all
![image](https://user-images.githubusercontent.com/1099479/37389037-00293da2-2763-11e8-933f-3b173a417016.png)

But I guess we need more feedback to decide.

**Comment by jodator** [comment]
AFAIR I was mostly influenced by GDocs when implementing split button's behavior.

**Comment by oleq** [comment]
Maybe the odd feeling is caused by the (relatively) big dropdown arrow?

**Comment by Reinmar** [comment]
Hm... I don't think so. I still think this is about those sharp corners. I find GDocs's implementation odd too.

But if no one else shares this feeling then you can just ignore it.

**Comment by mlewand** [comment]
The issue didn't get too much traction. In case someone finds it as a problem please feel free to add comments to this discussion and we'll reopen the issue.
