### ISSUE TITLE
how to remove all tooltip?

### ISSUE THREAD

**Issue by pasicopan** [ckeditor/ckeditor5-ui#387]
I don't need the tooltip, I have try to remove toolbar tooltip by
```
 Array.from(editor.ui.view.toolbar.items).forEach((button) => {
              button.tooltip = false;
              if (button.buttonView) {
                button.buttonView.tooltip = false;
              }
              // button.tooltipView = null;
            });
```
it works, but not enough. I can not find a way to remove the imagetoolbar tooltip.

btw, the tooltip has bug in ios, I have to click button twice to fire it, so I have to remove it all from the editor.

**Comment by Reinmar** [comment]
cc @oleq

**Comment by oleq** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/920.

Use CSS to remove tooltips

```css
.ck.ck-button .ck.ck-tooltip {
	display: none;
}
```

**Comment by Reinmar** [comment]
Hiding them with CSS is not a workaround for the iOS issue though, right? How can one remove the tooltips from image toolbar buttons too?

**Comment by oleq** [comment]
The snippet I pasted removes all tooltips from all buttons in the editor UI. Including the image toolbar. It's a nasty workaround. I proposed a similar one in https://github.com/ckeditor/ckeditor5-ui/pull/381 but from the JS side and we figured we should find a better solution to preserve tooltips and fix the actual bug.
