### ISSUE TITLE
Block toolbar UI improvements

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-ui#394]
Follow-up of https://github.com/ckeditor/ckeditor5-ui/pull/392.

![paragrah-too-strong](https://user-images.githubusercontent.com/1166967/40365050-09b604e8-5dd4-11e8-8363-dc707ea1cfe4.gif)

I wanted to report that paragraph is allways "on". Then I realised that it is only selected. However, I asked one more person "what is wrong with this panel" and he also said that paragraph is "on". We need a lighter style for focused items.

I want to make this ticket more generric to gather whole feedback about the UI of block toolbar in CKE 5.

**Comment by Reinmar** [comment]
cc @oleq @dkonopka

**Comment by Reinmar** [comment]
BTW, @oleq, I miss your new heading icons.

**Comment by oleq** [comment]
Me too! Haven't got enough time to finish them, though.

**Comment by oleq** [comment]
I propose 2 kinds of improvements:

## New icons

![kapture 2018-07-03 at 15 42 48](https://user-images.githubusercontent.com/1099479/42223410-f9ddbbf4-7ed7-11e8-9635-01a8853e6f38.gif)

![kapture 2018-07-03 at 15 44 09](https://user-images.githubusercontent.com/1099479/42223414-fbbd30f8-7ed7-11e8-81d9-590ab071a31b.gif)


## Focus style improvements 

**Note:** Old icons here as the new ones haven't been SVG'd yet.

![kapture 2018-07-03 at 15 28 51](https://user-images.githubusercontent.com/1099479/42222581-deb35f5c-7ed5-11e8-962c-4b99f5c55e4a.gif)
![kapture 2018-07-03 at 15 26 22](https://user-images.githubusercontent.com/1099479/42222573-da750328-7ed5-11e8-91b4-fc96d782cd44.gif)
![kapture 2018-07-03 at 15 27 36](https://user-images.githubusercontent.com/1099479/42222578-dcda74fe-7ed5-11e8-9ef0-ae2eefe5d699.gif)

**Comment by pjasiun** [comment]
I am not sure about serif pilcrow icon. We changed it to the simpler one since the whole UI is simple. The rest :+1:.

**Comment by Reinmar** [comment]
👍 For the pilcrow icon. Stylish and smooooth ;>

👍 For p/h1/h2/h3. Much better weight and alignment.

👍 For focus. I love the transitions.

**Comment by dkonopka** [comment]
More visible focus than ATM 👍 👍 👍

**Comment by scofalik** [comment]
Visually the serif icon looks better but it doesn't fit the rest of the toolbar, so I am torn. I also like a bigger padding - more space for clicking the button. Lastly, I wouldn't mind some kind of border or maybe only shadow, hinting that this icon is something clickable.

**Comment by Reinmar** [comment]
> Lastly, I wouldn't mind some kind of border or maybe only shadow, hinting that this icon is something clickable.

I had a similar feeling in the past. Perhaps we could do something about it (not necessarily in this ticket, though).
