### ISSUE TITLE
Consider using ButtonView inside ListItemView

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui#403]
As the framework develops, `ListItemView` becomes more and more like `ButtonView`:

* it `executes` when clicked,
* it has some keyboard support,
* [now it gets `isEnabled`](https://github.com/ckeditor/ckeditor5-ui/issues/389).

Soon it will get icons, tooltips, etc. and we'll have 2 components doing the same job.

Instead, I propose that we use `ButtonView` in `ListItemView` where the later is just a `<li>` DOM wrapper and an event/property proxy.

The button could have a special `type` for that purpose, or `LIV` would simply extend button's template and add a CSS class that changes its look.

cc @jodator @Reinmar @oskarwrobel

**Comment by jodator** [comment]
I second that - it gonna look almost 1:1 maybe with some minor changes (I don't see which actually so maybe invalid point) they do the practically the same.

Side note: wouldn't it help with creating nested dropdowns? :thinking: The dropdown button is just one step ahead to be added there - but it might be overkill for now as I don't know how we would manage opening cascade of dropdowns now.
