### ISSUE TITLE
Shouldn't the block toolbar disappear when the editor is blurred?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui#408]
This will look especially odd when it's used e.g. with an editor which has some toolbar (inline or balloon) because that toolbar will disappear once the editor loses the focus.

![jun-12-2018 13-43-47](https://user-images.githubusercontent.com/156149/41288467-b35dd53e-6e46-11e8-87ab-16d9d8b28b50.gif)

**Comment by Reinmar** [comment]
cc @oleq @oskarwrobel

**Comment by oskarwrobel** [comment]
BlockToolbar should be always visible in Letters so it should be configurable.

**Comment by Reinmar** [comment]
Why should it be always visible in Letters?

**Comment by oskarwrobel** [comment]
Because in Letters it is inside UI element and there is no need to hide it on blur.

**Comment by oskarwrobel** [comment]
I got used to permanently visible BlockToolbar in Letters and probably it's difficult for me to see this from a different pov. @pjasiun @dkonopka WDYT?

**Comment by pjasiun** [comment]
Block toolbar in Letters hides if the selection is in the title and if you blur Letters when selection is in the title, so for me it is fine if it disappears whenever you blur the editor. 

![block-toolbar](https://user-images.githubusercontent.com/1166967/41292683-8b5de6ca-6e53-11e8-9e76-656e7f6831a9.gif)
