### ISSUE TITLE
Shouldn't modal z-index be relative to the default one?

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#412]
https://github.com/ckeditor/ckeditor5-ui/blob/608525f324f26c9eff48fdf61c75e9110f5589c7/theme/globals/_zindex.css#L7-L8

```postcss
--ck-z-default: 1; 
--ck-z-modal: calc( var( --ck-z-default ) + 999 ); 
```

Then if you want to integrate CKE5 with a dialog you need override only the default z-index.

cc @oleq @dkonopka

**Comment by oleq** [comment]
Is there any case where overriding `--ck-z-default` while leaving the rest untouched makes sense?

**Comment by oskarwrobel** [comment]
I can't imagine anything reasonable but everything is possible :)

**Comment by oleq** [comment]
> Then if you want to integrate CKE5 with a dialog you need override only the default z-index.

Can you tell us more about that use-case? I'm not sure I got it right.

**Comment by oskarwrobel** [comment]
When you want to show CKE5 in dialog and dialog z-index is higher than `999` all balloons are displayed under the dialog. You need to bump z-index for the editor to be sure that all floating stuff will be over the dialog.

**Comment by oleq** [comment]
OK, that makes sense, I guess. PR please?
