### ISSUE TITLE
Balloon Toolbar sample does not work

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-ui#424]
![screen shot 2018-07-04 at 17 43 51](https://user-images.githubusercontent.com/1166967/42286063-dc975f48-7fb1-11e8-9318-19efbb3ca620.png)

**Comment by pjasiun** [comment]
This the the error you see when you open the sample.

**Comment by oleq** [comment]
This is because [`editableElement` is `null`](https://github.com/ckeditor/ckeditor5-ui/blob/master/src/toolbar/balloon/balloontoolbar.js#L62). Can you check this out @oskarwrobel?

**Comment by oskarwrobel** [comment]
Related https://github.com/ckeditor/ckeditor5-core/issues/137.
