### ISSUE TITLE
[Docs] Improve block toolbar guide

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-ui#427]
Classic editor with block toolbar does not make much sense, even if it is possible to run it there. Why should the user open the balloon toolbar if the icon could be in the main toolbar with the immediate access?

Second, guide misses the main point of introducing ballon toolbar. The problem balloon toolbar solves is: "How to insert a content (image, table) in the editor with balloon toolbar when the selection is collapsed?". If the only goal would be to change the block type, we would add these features to the balloon toolbar, and do not introduce 2 toolbars. We should mention inserting in the guide and add a feature which illustrates it (because of [this bug](https://github.com/ckeditor/ckeditor5-table/issues/27#issuecomment-396248812), the image might be better than the table).

**Comment by Reinmar** [comment]
@oleq, if you agree with us, please let us know if you'll be able to work on this this week. If not, we should reassign the ticket.

**Comment by Reinmar** [comment]
BTW, there's also a warning in this guide: 
![image](https://user-images.githubusercontent.com/156149/42619114-69b5a7d0-85b7-11e8-8699-91e62c47c23a.png)
