### ISSUE TITLE
Edge - SwitchButton - The square does not animate

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-ui#433]
As in the title.

The background color is animating but the square does not change its position.

**Comment by pomek** [comment]
![image](https://user-images.githubusercontent.com/2270764/42750478-a8396bee-88e7-11e8-8c62-8f1b5fd37b3c.png)

An animation from active to non-active works fine but from non-active to active does not work.

**Comment by oleq** [comment]
It's most likely because Edge does not like `calc( var( ` in transforms.  We could remove custom property definitions and use the values directly in the `transform` instead.

**Comment by dkonopka** [comment]
It's not even CSS Variables fault, [Edge is just broken with `calc()` and transitions/keyframes](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/105834).

![edge](https://user-images.githubusercontent.com/10219857/42752288-b2ff7a72-88ed-11e8-83d1-82a2913f6e8d.gif)

**Comment by Reinmar** [comment]
And they still didn't fix this

![image](https://user-images.githubusercontent.com/156149/42754629-731c3406-88f5-11e8-9a32-db501c024dcf.png)

;/ It's like 10 year old.
