### ISSUE TITLE
Translation for Blocktoolbar

### ISSUE THREAD

**Issue by MCMicS** [ckeditor/ckeditor5-ui#445]
I have set the language to German but the 'Edit Block' label will only be in English.
In Code I see no Translation for this.

see: https://github.com/ckeditor/ckeditor5-ui/blob/4a7f06fb1b6452b3c528a157a842e10a429f4517/src/toolbar/block/blocktoolbar.js#L214

**Comment by Reinmar** [comment]
The translations come from https://www.transifex.com/ckeditor/ckeditor5/ (feel free to join the project there). It might've been missing on the previous release, but I can see that German translation is complete now:

![image](https://user-images.githubusercontent.com/156149/46527878-a3948480-c892-11e8-85ab-d5cb5caed67a.png)

We plan a release next week, so you'll get all translations by then.

**Comment by MCMicS** [comment]
But I found no *.po file with this message. I've tested latest build from npm

**Comment by Reinmar** [comment]
The latest build was published 2 months ago. The translation was completed on Transifex later, so it's not released yet.

**Comment by MCMicS** [comment]
So the *.po file will publishe then in code?
I've expected that the default en.po file exists in code

**Comment by ma2ciek** [comment]
Hi, @MCMicS.

Thanks for reporting this issue. I've fixed it and added your translation suggestion on the https://www.transifex.com/ckeditor/ckeditor5/translate/#de/ckeditor5-ui/154458859. It will be available in the next release, which we plan to do soon.

**Comment by MCMicS** [comment]
Thanks
