### ISSUE TITLE
Setting a custom css class on dropdownview

### ISSUE THREAD

**Issue by lucasreppewelander** [ckeditor/ckeditor5-ui#447]
Hi, I cant really find that it is possible to set a custom css class to the dropdown view today. or am I wrong?

**Comment by lucasreppewelander** [comment]
I do have a local branch that solves this issue, proved and tested. When I tries to push my branch (named: `t/447`) it says I don't have the permission to do so. How am I supposed to do?

First time contributing to others code on github.

**Comment by oleq** [comment]
You're right, we don't have an option to set a CSS class on the [`DropdownView`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_dropdown_dropdownview-DropdownView.html) (as a whole) yet. You can add a custom class to the dropdown's button, though. Use the [`dropdownView.buttonView.class`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_button_buttonview-ButtonView.html#member-class) property.

If you feel like our code could be better and want to contribute, check out the [contributors guide](https://github.com/ckeditor/ckeditor5/blob/master/CONTRIBUTING.md) explaining where to start and how to [make a pull request](https://github.com/ckeditor/ckeditor5/blob/master/CONTRIBUTING.md#making-a-pull-request).

**Comment by lucasreppewelander** [comment]
Yes, I saw that, but in my case I actually needs to style the `DropdownPanelView` which does not have the ability to set the class too. And with the fact that you can't select a parent with pure css I think that this needs to be handled by the `DropdownView`

so I felt that setting the class on the `DropdownView` is more convenient especially in a plugin where you do things to the dropdownview anyway, like binds and such.

**Comment by oleq** [comment]
Big thanks for your contribution @lucasreppewelander!
