### ISSUE TITLE
Third party Ui how set font-family

### ISSUE THREAD

**Issue by balunaidu** [ckeditor/ckeditor5-ui#466]
i need third party ui but i try to do for font-family it;s not working. how to do that

**Comment by Reinmar** [comment]
I'm sorry, but your question is a bit unclear. Do you mean that you're building a third-party UI for CKEditor 5 (this is – your custom UI)? And that you try to apply font-family in the editor content?

If I understood you correctly, then the answer is in https://ckeditor.com/docs/ckeditor5/latest/features/font.html#common-api

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
