### ISSUE TITLE
Review approach to falsy values in Template definition

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui#47]
A followup of #27.

At the moment `Template.bind()` [casts "falsy" values to strings](https://github.com/ckeditor/ckeditor5-ui/blob/master/tests/template.js#L1050-L1076) which collides with [default behaviour of styles](https://github.com/ckeditor/ckeditor5-ui/blob/master/tests/template.js#L426-L438), which are handled as no value (like native `el.style.width = false`).

It should be unified, behaviour of styles is probably the best one.

**Comment by oleq** [comment]
The approach implemented in https://github.com/ckeditor/ckeditor5-ui/pull/51 works in such a way that all (`false`, `undefined`, `null`, etc.) but 0 (`Number`) are "falsy", which results in: 
* static DOM attribute not set at all, if it's value is falsy
* `bind.to()` ignored (not contributing to the DOM attribute) if bound model attribute value is falsy
* `bind.if()` removing DOM attribute if bound model attribute value is falsy

I decided that treating 0 (`Number`) as "non–falsy" value will be easier for developers to create bindings like

```js
Model( {
    foo: 20 // It's a Number.
} );

new Template( {
    attributes: {
        data-id: bind.to( 'foo' )
    }
} );
```

without explicit casting the value to string, which would be needed if 0 (`Number`) was "falsy"

```js
Model( {
    foo: 20 // It's a Number
} );

new Template( {
    attributes: {
        // data-id would not be set at all without this casting callback
        data-id: bind.to( 'foo', v => '' + v ) 
    }
} );
```

**Comment by Reinmar** [comment]
Just a note – we prefer more direct conversions:

```js
data-id: bind.to( 'foo', v => String( v ) )
```

**Comment by oleq** [comment]
Yeah, ` v => '' + v` wouldn't pass JSHint anyway, I guess.
