### ISSUE TITLE
[UX] White and empty color tiles should not look the same

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui#475]
This is confusing:

<img width="681" alt="Screenshot 2019-04-02 at 11 12 50" src="https://user-images.githubusercontent.com/1099479/55391148-0cef0a80-5539-11e9-80cb-d3ee7daca753.png">

cc @dkonopka @msamsel

**Comment by oleq** [comment]
I guess the empty one should rather be transparent, i.e. gray.

**Comment by dkonopka** [comment]
Agree, but I want to add there is missing label above "last used colors", I have no idea how we missed it before 😱

**Comment by oleq** [comment]
Looks like the issue was resolved at some point when fixing other issues 
![image](https://user-images.githubusercontent.com/1099479/64594717-d43d4200-d3b0-11e9-9bfa-4ad02bcb9a5e.png)
