### ISSUE TITLE
Rethink the architecture of UI framework and lib

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui#48]
Currently we've got a bit of mess here, because:

* ckeditor5-ui includes the framework and bindings for the default library
* ckeditor5-ui-default includes the default UI lib using the framework

The problem is with the bindings and framework laying in one repository. These are completely different levels because it should look like this:

* there's a framework,
* it's used by a default UI lib (which is generic in terms of a project),
* the editor features may need some bindings which main role should be to ease a use of the default UI lib in context of the editor.

So it looks like we should keep the code in 3 separate projects, however:

* It adds a bit to the complexity (many changes will touch at least two repos – UI lib and bindings for it or the framework and UI lib).
* CKEditor can be used without the UI lib anyway, because features are implemented in such a way that their engine and UI parts are kept separately.
* Other use cases for extending the UI library are generally still very blurry for us. It's generally about the community being able to define more components and how to make them reusable. All that should not be an issue.
* Another use case was about overriding the whole "view" layer of the default UI lib with some custom views (e.g. using different theming engine). This can always be achieved by simply adding another `ckeditor5-ui-*` package that will replace the existing one on the compilation step.
* And the last use case was another project using the default UI lib. That case is the least likely to happen and is the only that might in any way benefit from keeping the code in 3 repos. But even that isn't certain because so far implemented components are very generic and editor-independent. There are very few bindings (actually – the existing ones don't even have much sense at the moment) and they are kept separately (so don't have to be used by the other project).

So if only we make sure that the UI components we implement are not tightly bound to CKEditor, I think that we can safely keep the code in one repository.

cc @fredck and @oleq.

**Comment by oleq** [comment]
So your idea is basically to merge `ckeditor5-ui` with `ckeditor5-ui-default` into something like

````
ckeditor5-ui/
   src/
     view.js
     controller.js
     components/
        button/
          button.js
```

right?

**Comment by oleq** [comment]
What confuses me in current architecture is that bindings (like toolbar) belong to `ckeditor5-ui` repository, which has nothing to do with actual components but provides a framework. I think that if we decided to move bindings to `ckeditor5-ui-default`, the probability of parallel changes in 2 repositories would decrease. Then I'd stick to double–repository architecture we have at the moment.

I know that bindings are not exactly a `ckeditor5-ui-default` type of classes but they're semantically closer to that repo than to `ckeditor5-ui`, that's for sure. I'd wait for more bindings to come, observe the development of the project and postpone this discussion.

WDYT?

**Comment by Reinmar** [comment]
Replying to: https://github.com/ckeditor/ckeditor5-ui/issues/48#issuecomment-233612248

Rather:

```
ckeditor5-ui/
  src/
    view.js
    controller.js
    components/
       button/
         button.js
    bindings/
       button.js     
```

Where in components we'll have the contents of ckeditor5-ui-default. 

In very short – I propose to simply merge those two repositories that we have currently. There are multiple reasons why I don't think that keeping them separately makes much sense, one of them being that we should have 3 repositories actually. The current state is totally wrong because in ckeditor5-ui we have the framework and the bindings, so the 2 opposite layers (the middle layer is kept in ckeditor5-ui-default).

**Comment by oleq** [comment]
How about

> I think that if we decided to move bindings to ckeditor5-ui-default, the probability of parallel changes in 2 repositories would decrease. Then I'd stick to double–repository architecture we have at the moment.

**Comment by Reinmar** [comment]
So ckeditor5-ui would keep the framework and ckeditor5-ui-default the library? Sounds legit.

**Comment by Reinmar** [comment]
We need to answer one question, though – why are things separated?

My initial post suggests multiple use cases, but also points out that they don't mean that we need to separate the code:

> So if only we make sure that the UI components we implement are not tightly bound to CKEditor, I think that we can safely keep the code in one repository.

However, having a framework and lib in other repositories sounds good as it's based on significant application layers. These two packages have different concerns. The framework cares only about being useful and stable. The UI lib about providing proper components and UI/UX.

**Comment by oleq** [comment]
> So ckeditor5-ui would keep the framework and ckeditor5-ui-default the library? Sounds legit.

ckeditor5-ui: framework
ckeditor5-ui-default: components + bindings

It is what I meant in https://github.com/ckeditor/ckeditor5-ui/issues/48#issuecomment-233613671.

**Comment by Reinmar** [comment]
> ckeditor5-ui-default: components + bindings

Yeah, by writing "library" I meant "components + bindings".

**Comment by oleq** [comment]
Alright, so we have a plan. I'll do this thing after closing several other iteration2 issues.
