### ISSUE TITLE
Misleading docs of Template#apply

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5-ui#481]
## Is this a bug report or feature request?

🐞 Bug report

## 💻 Version of CKEditor

CKEditor v5 @ 12.1.0 and earlier

## 📋 Steps to reproduce

Looks like Templates are not applying text nodes when called with `apply` method.

There's a code following code listing [in our documentation](https://ckeditor5.github.io/docs/nightly/ckeditor5/12.0.0/api/module_ui_template-Template.html#function-apply):

```js
const element = document.createElement( 'div' );
const bind = Template.bind( observable, emitter );

new Template( {
    attrs: {
        id: 'first-div',
        class: bind.to( 'divClass' )
    },
    on: {
        click: bind( 'elementClicked' ) // Will be fired by the observable.
    }
    children: [
        'Div text.'
    ]
} ).apply( element );

element.outerHTML == "<div id="first-div" class="my-div">Div text.</div>"
```

On the other hand I checked `Template#render()` and it does add text node correctly.

Here's an example code that I have used to produce the problem:

```js
const element = document.createElement( 'div' );
const observable = new Model( {
	divClass: 'my-div'
} );
const emitter = Object.create( EmitterMixin );

const bind = Template.bind( observable, emitter );
new Template( {
	attributes: {
		id: 'first-div',
		class: bind.to( 'divClass' )
	},
	children: [
		'Div text.'
	]
} ).apply( element );

console.log( element.outerHTML );
```

## ✅ Expected result

```html
<div id="first-div" class="my-div">Div text.</div>
```

being logged into the console.

## ❎ Actual result

```html
<div id="first-div" class="my-div"></div>
```

**Comment by oleq** [comment]
For implementation reasons, `Template#apply` does not create new DOM Nodes. See https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_template-Template.html#function-apply.

**Comment by mlewand** [comment]
Thanks @oleq - in that case I'm closing this issue. I used code listing for reference and it clearly hinted that text node should be created.

**Comment by oleq** [comment]
Long story short, it's impossible to create nodes using our template syntax when there already some in the Node the template is applied to. No way to tell where to create a new node (before existing ones, after, etc.?). We decided in the past that this would be very confusing if we allowed that.

**Comment by oleq** [comment]
> I used code listing for reference and it clearly hinted that text node should be created.

I suppose the doc string is wrong and should be fixed.

**Comment by mlewand** [comment]
This particular problem is already tracked in ckeditor/ckeditor5#1648.
