### ISSUE TITLE
It should be possible to open ContextualBalloon without arrow.

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-ui#487]
The `ContextualBalloon` API allows to pass custom positions but it lacks the ability to show/hide arrow for it. At the moment all features uses arrow but `MentionUI` does not. While working on https://github.com/ckeditor/ckeditor5-mention/issues/27 I've realised that `MentionUI` should use `ContextualBalloon` as well to work well with other features.

Proposal:

1. Add `withArrow` property to the balloon positions:

```js
BalloonPanelView.defaultPositions = {
	// ------- North

	northArrowSouth: ( targetRect, balloonRect ) => ( {
		top: getNorthTop( targetRect, balloonRect ),
		left: targetRect.left + targetRect.width / 2 - balloonRect.width / 2,
		name: 'arrow_s',
		withArrow: true
	} ),

	// ...
};
```

So the default value would be `false` - but it will be a breaking change AFAICS. The backward compatible change would be to default it to `true` but the code might get a bit less elegant.

2. Add switch to `ContextualBalloon.add()` options:

```js
this._balloon.add( {
	view: this._mentionsView,
	position: { /* position data  */ } ),
	withArrow: false
} );
```

/cc @oleq WDYT

**Comment by jodator** [comment]
OK so after starting implementing this I can see the second option to work better:

```js
this._balloon.add( {
	view: this._mentionsView,
	position: this._getBalloonPanelPositionData( markerMarker, this._mentionsView.position ),
	withArrow: false
} );
```

**Comment by oleq** [comment]
`withArrow` here controls `BalloonPanelView#withArrow` here? I'm OK with it. 

The biggest problem here is that we do not have an API that would make using `BalloonPanelView.defaultPositions` possible when there is no arrow. They will be shifted by the arrow offset. 

I suppose that when `withArrow: false` we should use another set of positions that precisely attach to the corner of the `BPV` to the target.

**Comment by jodator** [comment]
> I suppose that when `withArrow: false` we should use another set of positions that precisely attach to the corner of the `BPV` to the target.

It links to the issue of adding [more positions to `BPV`](https://github.com/ckeditor/ckeditor5-ui/issues/485) so ones without arrow might be added as well.

Here I'm using custom positions as those with arrows are shifted and I'm interested in ones without that shift - hence custom.

**Comment by mlewand** [comment]
Just my 2 cents: The property name could be simplified to `arrow` alone.

> The biggest problem here is that we do not have an API that would make using `BalloonPanelView.defaultPositions` possible when there is no arrow. They will be shifted by the arrow offset.

Regarding `BalloonPanelView.defaultPositions` it would make sense for it to be arrow-agnostic. I mean we should only consider balloon panel positions there. The arrow would be treated as an additional component inside of the balloon panel. If present it should automatically calculate arrow position as a next step only after the main component position is determined.

That way we'll have much less variations of `BalloonPanelView.defaultPositions` value.

But in order to do that I think that the context balloon context should keep the pointed element/target in it's state, and from what i see now it doesn't do that.

**Comment by jodator** [comment]
> Just my 2 cents: The property name could be simplified to `arrow` alone.

I'm against - it's a boolean value so simply `arrow` doesn't say match. Also there already [BalloonPanelView#withArrow](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_panel_balloon_balloonpanelview-BalloonPanelView.html#member-withArrow) so the property is named after that.

For the `BPV` I have mixed feelings (besides that's an off-topic here). Would be lovely if they be arrow agnostic but OTOH the position must be shifted accordingly to the arrow head (and it's width). It might be "hard" to pick that shift value based on state of `withArrow`.

**Comment by mlewand** [comment]
> Also there's already a [BalloonPanelView#withArrow](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_panel_balloon_balloonpanelview-BalloonPanelView.html#member-withArrow) property so I've named this option after that.

In that case using `withArrow` is more reasonable option, wasn't aware of that.
