### ISSUE TITLE
ColorGridView tests fail on CI

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui#488]
https://travis-ci.org/ckeditor/ckeditor5-ui/builds/521411178

**Comment by msamsel** [comment]
Issues seems to be resolved by @oleq, with https://github.com/ckeditor/ckeditor5-ui/commit/b2dcebe3b8578eced103699a7ff812c8818527e4

master is not failing now:
https://travis-ci.org/ckeditor/ckeditor5-ui/branches

**Comment by mlewand** [comment]
@msamsel that's right the issue has been addressed in referenced commit. Thanks for pointing this out.
