### ISSUE TITLE
Does model passed to the controllers constructor needs to be an instance of the model class?

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-ui#74]
Does model passed to the controllers constructor needs to be an instance of the model class?

https://github.com/ckeditor/ckeditor5-ui/blob/eca89ac35ad4b14896a05a6b1c2c8d67ceb52086/src/controller.js#L22

Can't it be just an `Observable`?

**Comment by pjasiun** [comment]
Note that here we passed to it something what is not a `Model`:

https://github.com/ckeditor/ckeditor5-ui-default/blob/d4a6ee75e5ef50317fd0637c86c6b79a61522eeb/src/editableui/editableui.js#L24

**Comment by oleq** [comment]
`Controller` class has been removed in #95.
