### ISSUE TITLE
Lack of useCapture option in DOMEmitterMixin

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#76]
There is no way to set `useCapture` option in `DOMEmitterMixin`
https://github.com/ckeditor/ckeditor5-ui/blob/master/src/domemittermixin.js#L70

I need this option in `FocusManager` for listening `focus` and `blur` events which don't bubble. Unfortunately `focusin` and `focusout` (the bubbling ones) are not supported by FF.

**Comment by Reinmar** [comment]
CKEditor 4 tried not to use capturing and e.g. a focus manager knew about every focusable element. It may give a bit more control.

**Comment by oskarwrobel** [comment]
CKE4 uses capturing https://github.com/ckeditor/ckeditor-dev/blob/master/core/focusmanager.js#L183

**Comment by Reinmar** [comment]
Haha... good to know :D.
