### ISSUE TITLE
ComponentFactory should be moved

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-ui#77]
As far I understand the UI framework should not know anything about the editor. This is why ComponentFactory should be moved:

https://github.com/ckeditor/ckeditor5-ui/blob/eca89ac35ad4b14896a05a6b1c2c8d67ceb52086/src/componentfactory.js#L31

I think it should be together with the EditorUi class (https://github.com/ckeditor/ckeditor5-ui-default/blob/23a508f50747b5349937620b0387649bc4480489/src/editorui/editorui.js). These classes together, define expected API of the frontend Editor.

**Comment by Reinmar** [comment]
This bit is tricky... It's a more of editor core, together with `EditorUI` in fact. Those classes are necessary to create editors with UI. Core defines some editors and defines also a type of editor which has an UI... while not knowing about the UI library. So all this is a bit tangled.

Perhaps this will clarify itself a bit when we fix things like https://github.com/ckeditor/ckeditor5/issues/303 and https://github.com/ckeditor/ckeditor5/issues/327. Maybe the UI library will then simply define an editor interface which needs to be implemented and that interface will tell that `editor.ui` must be defined.

**Comment by oleq** [comment]
Closed in https://github.com/ckeditor/ckeditor5-editor-classic/issues/38.
