### ISSUE TITLE
Rename `tag` to `element` in TemplateDefinition

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-ui#78]
I've noticed that [we're using the unfortunate name `tag` in the template definition](https://github.com/ckeditor/ckeditor5-ui/blob/bd26baea1ae91eff4aba8c80f812bc2dda31f339/src/template.js#L1011). I propose to change it to `element`.

Elements have "names", which is the value we expect there. A tag is instead the string that represents either the opening or the closing markup of elements in HTML. For example, `<div class="x">` is a tag, as well as `</div>`.

But yes, we were used to refer to elements as `tags`... kinda 10 years ago. Nowadays it's pretty inappropriate and gives that unprofessional feeling that we so much dislike.

**Comment by oleq** [comment]
I'm handling this along with https://github.com/ckeditor/ckeditor5-ui/issues/262. 

I'd go with `name` instead. It's shorter and makes sense. OTOH `tagName` would be better because it corresponds with the [native property](https://developer.mozilla.org/en-US/docs/Web/API/Element/tagName).

```js
new Template( {
    name: 'div',
    attributes: {
    }
} );
```
vs.

```js
new Template( {
    element: 'div',
    attributes: {
    }
} );
```
vs.
```js
new Template( {
    tagName: 'div',
    attributes: {
    }
} );
```
WDYT?

**Comment by fredck** [comment]
For me `element` still makes it totally obvious. I don't think we need to rethink it.

**Comment by Reinmar** [comment]
So does `tag` and it's shorter and correct (from the DOM perspective too). Actually, `element` is worse and so does `name` becuase they are both less direct.

**Comment by oleq** [comment]
Since we developed many views and no one complained so far + natively the property is called `tagName` (e.g. `document.body.tagName`) I think this issue is settled.
