### ISSUE TITLE
Exception on stopListening() of DOMEmitterMixin

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#83]
How to reproduce:

```javascript
const emitter = Object.create( DOMEmitterMixin );

emitter.listenTo( element, 'someEvent', callback );
emitter.stopListening( element, 'someEvent', callback );

emitter.stopListening(); // TypeError: Cannot read property 'removeListener' of undefined.
```

This works fine:
```javascript
const emitter = Object.create( DOMEmitterMixin );

emitter.listenTo( element, 'someEvent', callback );
emitter.stopListening( element, 'someEvent' ); // Without callback

emitter.stopListening();
```

**Comment by Reinmar** [comment]
This may be needed for https://github.com/ckeditor/ckeditor5/issues/114.

**Comment by oskarwrobel** [comment]
This is because parent `EmitterMixin.off( event, callback )` removes only specified callback from callbacks array, and keeps `event` object in memory even if callbacks array is empty (is it expected?).

We can easily fix it by adding condition which prevent from removing non existing listener [here](https://github.com/ckeditor/ckeditor5-ui/blob/master/src/domemittermixin.js#L244-L246) or we can consider to improve `EmitterMixin.off()` to remove event from emitter when callbacks array is empty.
