### ISSUE TITLE
It should be possible to skip some elements on the collection binding

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-ui#92]
It would be a nice feature if I could skip some elements on binding collection:

``` js
itemsControllerCollection.bind( modelItems ).as( ( modelItem ) => {
    if ( modelItem.hidden ) {
        return null;
    } else {
        const itemView = new ItemView( editor.locale );
        return new Controller( modelItem, itemView );
    }
} );
```

It should be doable, even with a nice position mapping.

**Comment by pjasiun** [comment]
During moving collection binding from the `CollectionController` to the `ViewCollection` this functionality has been removed.

**Comment by pjasiun** [comment]
Of course the sample code now should looks like:
```
viewCollection.bind( modelItems ).as( ( modelItem ) => {
    if ( modelItem.hidden ) {
        return null;
    } else {
        return new ItemView( editor.locale );
    }
} );
```

**Comment by oleq** [comment]
A related issue https://github.com/ckeditor/ckeditor5-ui/issues/98.

**Comment by pjasiun** [comment]
Also related: https://github.com/ckeditor/ckeditor5-utils/issues/125
