### ISSUE TITLE
Problem with id property in view class

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#93]
`id` property could be a [common property](https://github.com/ckeditor/ckeditor5-ui-default/blob/master/src/inputtext/inputtextview.js#L34) for input components, but using this property can blow up the editor. It happens when `View` instance is beeing [added to the views collection](https://github.com/ckeditor/ckeditor5-ui/blob/master/src/controller.js#L220). This is because `id` property is [reserved](https://github.com/ckeditor/ckeditor5-utils/blob/master/src/collection.js#L55) for collection item and has to be a `String`.

**Comment by Reinmar** [comment]
But `id` is under `attributes`. So it shouldn't collide with the id used by the collection, right?

BTW:

* we don't use access by id anywhere yet, I think,
* the property id name is configurable in the collection.

**Comment by oskarwrobel** [comment]
When you add eg [this](https://github.com/ckeditor/ckeditor5-ui-default/blob/master/src/inputtext/inputtext.js#L33) component as collection item it will blow up.

**Comment by oskarwrobel** [comment]
Hm... Now I think that it is not a huge problem so I'm removing high priority from this issue.

**Comment by Reinmar** [comment]
Ah, ok. The view has an "id" property. Makes sense now.

When fixing this we'll need to figure out whether we need those id properties in the collection items at all. Perhaps they could just be turned into symbols.
