### ISSUE TITLE
Remove the Controller class

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui#95]
All changes required to remove the `Controller` class.
1. `View#createCollection()`.
2. Add `ViewCollection()` (if needed).
3. Make that `ViewCollection` instance can be used directly in a template and that `view.someCollection.add( someView )`  or `remove( someView )`.
4. Verify `init()` and `destroy()` chains.

**Comment by pjasiun** [comment]
Should fix https://github.com/ckeditor/ckeditor5-ui/issues/90 and https://github.com/ckeditor/ckeditor5-ui/issues/91.

**Comment by oleq** [comment]
`package.json` for the entire refac in https://github.com/ckeditor/ckeditor5/tree/mvc-refac branch.
