### ISSUE TITLE
Pass index to custom callback in controllers binding

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#98]
Right now is:

``` javascript
        controllers.bind( data ).as( ( item, locale ) => {
            if ( !item.foo ) {
                return null;
            } else if ( item.foo == 'bar' ) {
                return new BarController( ..., BarView( locale ) );
            } else {
                return new DifferentController( ..., DifferentView( locale ) );
            }
        } );
```

and I'm thinking about something like this:

``` javascript
        controllers.bind( data ).as( ( item, locale, index ) => {
            if ( item.inactive ) {
                return null; // Does not increment index.
            } else if ( index < 10 ) {
                return new Controller( ..., FullView( locale );
            } else {
                return new Controller( ..., CompactView( locale );
            }
        } );
```

Question is what will happen when new item will be added at the top of already rendered collection?

**Comment by oleq** [comment]
To work like this, the entire `ViewCollection` would need to be re–rendered because current implementation assumes that once added, the `View` is immutable – it does not change it's class as long as it belongs to the `VC`.

It is possible to implement it, but the question is do we really need it? Could an additional `controllers.on( 'add', ... )` listener handle a necessary transformation?

**Comment by oleq** [comment]
This issue is still valid but for `ViewCollection` because `Controller` class is gone now (#95).

**Comment by oleq** [comment]
@oskarwrobel Does https://github.com/ckeditor/ckeditor5-utils/issues/215 fix this issue?

**Comment by oskarwrobel** [comment]
Nope. But I'm not sure if this is something that we need anymore. `CollaborativeComments` uses something similar because collapsed comment displays only the first and the last comment but there is an additional view between those comments:
```
Models:                Views:
[ Comment 1 ]
[ Comment 2 ]          [ Comment 1 ]
[ Comment 3 ]  ----->  [ Additional view counter ]
[ Comment 4 ]          [ Comment 5 ]
[ Comment 5 ]
```
And this is handled by an additional collection that is between collection of all models and view collection:
```
All models:            Filtered models:       Views:
[ Comment 1 ]
[ Comment 2 ]          [ Comment 1 ]          [ Comment 1 ]
[ Comment 3 ]  ----->  [ Counter   ]  ----->  [ Counter ]
[ Comment 4 ]          [ Comment 5 ]          [ Comment 5 ]
[ Comment 5 ]
```

**Comment by Reinmar** [comment]
I assume this is not relevant anymore.
